# Generated by Django 5.0.7 on 2024-11-22 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_adminprofile_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
