# Generated by Django 5.0.7 on 2024-11-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_feedback_delete_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='admin_in_charge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
